services:
  database:
    image: postgres:latest
    container_name: cryptocurrency_platform_database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
       - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cryptocurrency_platform_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./frontend
    container_name: cryptocurrency_platform_frontend
    ports:
     - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata: