services:
  database:
    image: postgres:latest
    container_name: cryptocurrency_platform_database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
       - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cryptocurrency_platform_backend
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  pgdata: